### PR TITLE
i214: make emailAuthOptionsScreen scrollable

### LINKED ISSUE #214: Keyboard can be over the top of text fields and buttons
#### Describe the bug

The keyboard sometimes hides UI the user needs 

#### To Reproduce
1. Go to OtherAuthOptionsPage 
2. Click on a textfield 
3. See the keybaord is over the Submit Button and bottom text field on small phones 

#### Expected behavior
Be able to scroll 

- [ ] Put all pages with textfields in a scrollable

### PR DESCRIPTION
**Pull request by tamari-gray**
Fixes #214

### CODE REVIEW

File: lib/widgets/auth/email_auth_options_page.dart [hunk 1]
```diff
@@ -19,62 +19,55 @@ class EmailAuthOptionsPage extends StatelessWidget {
...
+          color: Colors.black,
         ),
-        body: StoreConnector<AppState, VmEmailAuthOptionsPage>(
-          distinct: true,
-          converter: (store) => store.state.emailAuthOptionsPage,
-          builder: (context, vm) {
-            if (vm.step != AuthStep.waitingForInput) {
-              return Center(child: CircularProgressIndicator());
-            }
-            return Center(
```
Comment (tamari-gray) [inline lib/widgets/auth/email_auth_options_page.dart:36]: i removed uneccessary Columns, Containers. These were to help with layout in old redundant 'otherAuthOptionsPage'

**Review by tamari-gray — COMMENTED** [review]
think shes good :)

**Review by nickmeinhold — APPROVED** [review]
So good!  Thanks heaps!!!
